nw.Register( 'Kate_Location' )
  :Write( net.WriteString )
  :Read( net.ReadString )
  :SetGlobal()

nw.Register( 'Kate_FirstJoin' )
  :Write( net.WriteUInt, 31 )
  :Read( net.ReadUInt, 31 )
  :SetLocalPlayer()
  :Accessor( 'FirstJoin' )

nw.Register( 'Kate_LastJoin' )
  :Write( net.WriteUInt, 31 )
  :Read( net.ReadUInt, 31 )
  :SetLocalPlayer()
  :Accessor( 'LastJoin' )

nw.Register( 'Kate_SessionStarted' )
  :Write( net.WriteUInt, 31 )
  :Read( net.ReadUInt, 31 )
  :SetLocalPlayer()
  :Accessor( 'SessionStarted' )

nw.Register( 'Kate_Playtime' )
  :Write( net.WriteUInt, 31 )
  :Read( net.ReadUInt, 31 )
  :SetLocalPlayer()

nw.Register( 'Kate_ExpireUserGroup' )
  :Write( net.WriteString )
  :Read( net.ReadString )
  :SetLocalPlayer()
  :Accessor( 'ExpireUserGroup' )

nw.Register( 'Kate_ExpireTime' )
  :Write( net.WriteUInt, 31 )
  :Read( net.ReadUInt, 31 )
  :SetLocalPlayer()
  :Accessor( 'ExpireTime' )

nw.Register( 'Kate_Mentor' )
  :Write( net.WriteString )
  :Read( net.ReadString )
  :SetLocalPlayer()
  :Accessor( 'Mentor' )

nw.Register( 'Kate_Cloak' )
  :Write( net.WriteBool )
  :Read( net.ReadBool )
  :SetLocalPlayer()
  :Accessor( 'Cloak' )

nw.Register( 'Kate_ReturnPos' )
  :Write( net.WriteVector )
  :Read( net.ReadVector )
  :SetLocalPlayer()
  :Accessor( 'ReturnPos' )