nw.Register("mute")
	:Write(net.WriteUInt, 31)
	:Read(net.ReadUInt, 31)
	:SetLocalPlayer()
	:Accessor("Mute")

nw.Register("gag")
	:Write(net.WriteUInt, 31)
	:Read(net.ReadUInt, 31)
	:SetLocalPlayer()
	:Accessor("Gag")

nw.Register("play_time")
	:Write(net.WriteUInt, 31)
	:Read(net.ReadUInt, 31)
	:SetLocalPlayer()
	:Accessor("PlayTime")

nw.Register("first_join")
	:Write(net.WriteUInt, 31)
	:Read(net.ReadUInt, 31)
	:SetLocalPlayer()
	:Accessor("FirstJoin")

nw.Register("last_seen")
	:Write(net.WriteUInt, 31)
	:Read(net.ReadUInt, 31)
	:SetLocalPlayer()
	:Accessor("LastSeen")

nw.Register("return_pos")
	:Write(net.WriteVector)
	:Read(net.ReadVector)
	:SetLocalPlayer()
	:Accessor("ReturnPos")

nw.Register("cloak")
	:Write(net.WriteBool)
	:Read(net.ReadBool)
	:SetPlayer()
	:Accessor("Cloak")